import {
  asAdventureNodeId,
  asChildId,
  asCollectionId,
  asLearningNodeId,
  asMemoryNodeId,
  asRelationshipId,
  asWorldNodeId,
} from "@/intelligence/types/ids";
import type { AdventureNode } from "@/intelligence/types/adventure";
import type { LearningNode } from "@/intelligence/types/learning";
import type { MemoryNode } from "@/intelligence/types/memory";
import type { GraphRelationship } from "@/intelligence/types/relationships";
import type { WorldNode } from "@/intelligence/types/world";

const NOW = "2026-01-01T00:00:00.000Z";

/**
 * Minimal reference seed — proves the architecture, not a content catalog.
 * Fire Truck is the reference World Node.
 */

export const SEED_WORLD_NODES: WorldNode[] = [
  {
    id: asWorldNodeId("world_fire_truck"),
    slug: "fire_truck",
    name: "Fire Truck",
    category: "Vehicles",
    subCategory: "Emergency",
    description:
      "A special emergency vehicle that carries firefighters and equipment to help people during fires and emergencies.",
    aliases: ["firetruck", "fire engine", "fire engine truck"],
    tags: ["emergency", "community", "red", "siren"],
    parentIds: [],
    childIds: [],
    relatedNodeIds: [
      asWorldNodeId("world_ambulance"),
      asWorldNodeId("world_police_car"),
      asWorldNodeId("world_firefighter"),
    ],
    collections: [asCollectionId("collection_community_helpers")],
    learningObjectiveIds: [],
    defaultAdventureIds: [asAdventureNodeId("adventure_community_helpers")],
    defaultMediaIds: [],
    difficulty: 1,
    estimatedAgeRanges: [
      { min: 2, max: 3 },
      { min: 4, max: 5 },
      { min: 6, max: 8 },
      { min: 9, max: 12 },
    ],
    emoji: "🚒",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: asWorldNodeId("world_ambulance"),
    slug: "ambulance",
    name: "Ambulance",
    category: "Vehicles",
    subCategory: "Emergency",
    description: "An emergency vehicle that helps people who are hurt or sick.",
    aliases: ["ambu"],
    tags: ["emergency", "community", "hospital"],
    parentIds: [],
    childIds: [],
    relatedNodeIds: [asWorldNodeId("world_fire_truck")],
    collections: [asCollectionId("collection_community_helpers")],
    learningObjectiveIds: [],
    defaultAdventureIds: [asAdventureNodeId("adventure_community_helpers")],
    defaultMediaIds: [],
    difficulty: 1,
    estimatedAgeRanges: [{ min: 2, max: 12 }],
    emoji: "🚑",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: asWorldNodeId("world_police_car"),
    slug: "police_car",
    name: "Police Car",
    category: "Vehicles",
    subCategory: "Emergency",
    description: "A car that helps keep people safe in the community.",
    aliases: ["police"],
    tags: ["emergency", "community", "safety"],
    parentIds: [],
    childIds: [],
    relatedNodeIds: [asWorldNodeId("world_fire_truck")],
    collections: [asCollectionId("collection_community_helpers")],
    learningObjectiveIds: [],
    defaultAdventureIds: [asAdventureNodeId("adventure_community_helpers")],
    defaultMediaIds: [],
    difficulty: 1,
    estimatedAgeRanges: [{ min: 2, max: 12 }],
    emoji: "🚓",
    createdAt: NOW,
    updatedAt: NOW,
  },
  {
    id: asWorldNodeId("world_firefighter"),
    slug: "firefighter",
    name: "Firefighter",
    category: "People",
    subCategory: "Community Helpers",
    description: "A person who helps put out fires and keeps people safe.",
    aliases: ["fire fighter", "fireman", "firewoman"],
    tags: ["community", "helping", "courage"],
    parentIds: [],
    childIds: [],
    relatedNodeIds: [asWorldNodeId("world_fire_truck")],
    collections: [asCollectionId("collection_community_helpers")],
    learningObjectiveIds: [],
    defaultAdventureIds: [asAdventureNodeId("adventure_community_helpers")],
    defaultMediaIds: [],
    difficulty: 1,
    estimatedAgeRanges: [{ min: 2, max: 12 }],
    emoji: "🧑‍🚒",
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const SEED_LEARNING_NODES: LearningNode[] = [
  {
    id: asLearningNodeId("learn_fire_truck"),
    worldNodeId: asWorldNodeId("world_fire_truck"),
    title: "Fire Truck Learning",
    minimumAge: 2,
    maximumAge: 12,
    difficulty: 1,
    category: "community",
    learningObjectives: ["recognize fire truck", "understand helping"],
    requiredKnowledge: [],
    relatedWorldNodeIds: [
      asWorldNodeId("world_ambulance"),
      asWorldNodeId("world_firefighter"),
    ],
    estimatedDurationMinutes: 5,
    languagesSupported: ["en", "es"],
    vocabulary: ["fire truck", "ladder", "hose", "siren", "firefighter"],
    pronunciation: "FIRE truk",
    funFacts: [
      "Fire trucks carry ladders so firefighters can help people high up.",
      "The loud siren asks everyone to make room.",
    ],
    quizQuestions: [
      {
        id: "q_ft_red",
        question: "Which one is often red?",
        choices: ["Fire Truck", "Banana", "Cloud"],
        answerIndex: 0,
      },
    ],
    wonderQuestions: ["Why do you think firefighters help people?"],
    conversationPrompts: ["What sound does a fire truck make?"],
    activities: ["Can you find another community helper today?"],
    stories: [],
    videos: [],
    songs: [],
    games: [],
    coloringPages: [],
    creatorContent: [],
    learningGoals: ["recognize fire truck", "understand helping"],
    ageVariants: [
      {
        ageRange: { min: 2, max: 3 },
        vocabulary: ["fire truck", "red", "truck", "wheel", "wee-woo"],
        funFacts: ["Fire trucks are often bright red so everyone can see them."],
        quizQuestions: [
          {
            id: "q_ft_2_wheels",
            question: "Can you point to the wheels?",
            choices: ["Yes!", "Maybe later"],
            answerIndex: 0,
          },
        ],
        wonderQuestions: ["Where does a fire truck sleep?"],
        conversationPrompts: ["Can you say fire truck?"],
        activities: ["Point to the ladder on a fire truck picture."],
        learningGoals: [
          "recognize fire truck",
          "identify red",
          "hear siren",
          "say fire truck",
        ],
        learningObjectives: [
          "recognize fire truck",
          "identify red",
          "hear siren",
          "say fire truck",
        ],
        requiredKnowledge: [],
        estimatedDurationMinutes: 3,
        difficulty: 1,
        category: "community",
        languagesSupported: ["en", "es"],
        learningLevel: 1,
        spanish: {
          word: "camión de bomberos",
          pronunciation: "kah-MYOHN deh boh-MEH-rohs",
        },
      },
      {
        ageRange: { min: 4, max: 5 },
        vocabulary: ["ladder", "hose", "emergency", "firefighter"],
        funFacts: [
          "Firefighters use hoses to spray water and help put out fires.",
        ],
        quizQuestions: [
          {
            id: "q_ft_4_help",
            question: "Who helps people with a fire truck?",
            choices: ["Firefighters", "Pirates", "Robots"],
            answerIndex: 0,
          },
        ],
        wonderQuestions: ["Why does a fire truck carry water?"],
        conversationPrompts: ["Why do firefighters wear helmets?"],
        activities: ["Draw a fire truck and count the wheels."],
        learningGoals: [
          "understand firefighters help people",
          "identify ladder and hose",
          "understand emergencies",
        ],
        learningObjectives: [
          "understand firefighters help people",
          "identify ladder and hose",
          "understand emergencies",
        ],
        requiredKnowledge: ["recognize fire truck"],
        estimatedDurationMinutes: 6,
        difficulty: 2,
        category: "community",
        languagesSupported: ["en", "es"],
        learningLevel: 2,
        spanish: {
          word: "camión de bomberos",
          pronunciation: "kah-MYOHN deh boh-MEH-rohs",
        },
      },
      {
        ageRange: { min: 6, max: 8 },
        vocabulary: ["pump", "teamwork", "community helper"],
        funFacts: [
          "Water pumps on fire trucks push water through long hoses with strong pressure.",
        ],
        quizQuestions: [
          {
            id: "q_ft_6_team",
            question: "Why do firefighters work as a team?",
            choices: [
              "Big jobs need many helpers",
              "They like matching coats",
              "Trucks only seat one person",
            ],
            answerIndex: 0,
          },
        ],
        wonderQuestions: ["How does the fire pump work?"],
        conversationPrompts: ["What other community helpers do you know?"],
        activities: ["Visit a fire station or watch a community helper video."],
        learningGoals: [
          "understand how water pumps work",
          "understand community helpers",
          "understand teamwork",
        ],
        learningObjectives: [
          "understand how water pumps work",
          "understand community helpers",
          "understand teamwork",
        ],
        requiredKnowledge: ["identify ladder and hose"],
        estimatedDurationMinutes: 8,
        difficulty: 3,
        category: "engineering",
        languagesSupported: ["en", "es"],
        learningLevel: 3,
        spanish: {
          word: "camión de bomberos",
          pronunciation: "kah-MYOHN deh boh-MEH-rohs",
        },
      },
      {
        ageRange: { min: 9, max: 12 },
        vocabulary: ["infrastructure", "emergency response", "hydraulics"],
        funFacts: [
          "Hydraulic systems use pressurized fluid to raise heavy ladders on fire trucks.",
        ],
        quizQuestions: [
          {
            id: "q_ft_9_compare",
            question: "How is a fire truck different from an ambulance?",
            choices: [
              "Fire trucks focus on fire and rescue; ambulances focus on medical care",
              "They are exactly the same",
              "Ambulances put out fires",
            ],
            answerIndex: 0,
          },
        ],
        wonderQuestions: [
          "How does hydraulic pressure power a ladder?",
        ],
        conversationPrompts: [
          "How does a city plan emergency response?",
        ],
        activities: [
          "Compare fire trucks, ambulances, and police cars in your neighborhood.",
        ],
        learningGoals: [
          "understand city infrastructure",
          "understand emergency response",
          "compare emergency vehicles",
        ],
        learningObjectives: [
          "understand city infrastructure",
          "understand emergency response",
          "compare emergency vehicles",
        ],
        requiredKnowledge: ["understand how water pumps work"],
        estimatedDurationMinutes: 10,
        difficulty: 4,
        category: "engineering",
        languagesSupported: ["en", "es"],
        learningLevel: 4,
        spanish: {
          word: "camión de bomberos",
          pronunciation: "kah-MYOHN deh boh-MEH-rohs",
        },
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  },
];
export const SEED_ADVENTURE_NODES: AdventureNode[] = [
  {
    id: asAdventureNodeId("adventure_community_helpers"),
    title: "Community Helpers",
    description:
      "Discover the people and vehicles that help keep our neighborhood safe.",
    coverImage: null,
    requiredNodeIds: [
      asWorldNodeId("world_fire_truck"),
      asWorldNodeId("world_ambulance"),
      asWorldNodeId("world_police_car"),
    ],
    optionalNodeIds: [asWorldNodeId("world_firefighter")],
    reward: {
      title: "Community Helper Explorer",
      points: 100,
      badgeId: "badge_community_helpers",
    },
    unlockRequirements: {
      minAge: 2,
    },
    recommendedAge: { min: 2, max: 10 },
    estimatedTimeMinutes: 30,
    progressRules: {
      unlockThreshold: 0.34,
      countOptionalTowardProgress: true,
    },
    completionRules: {
      requireAllRequiredNodes: true,
      minMemories: 3,
    },
    relatedAdventureIds: [],
    createdAt: NOW,
    updatedAt: NOW,
  },
];

export const SEED_RELATIONSHIPS: GraphRelationship[] = [
  {
    id: asRelationshipId("rel_ft_ambulance"),
    type: "LEADS_TO",
    fromGraph: "world",
    fromId: "world_fire_truck",
    toGraph: "world",
    toId: "world_ambulance",
    weight: 0.95,
    meta: { reason: "next_emergency_vehicle" },
    createdAt: NOW,
  },
  {
    id: asRelationshipId("rel_ft_police"),
    type: "RELATED_TO",
    fromGraph: "world",
    fromId: "world_fire_truck",
    toGraph: "world",
    toId: "world_police_car",
    weight: 0.85,
    createdAt: NOW,
  },
  {
    id: asRelationshipId("rel_ft_firefighter"),
    type: "RELATED_TO",
    fromGraph: "world",
    fromId: "world_fire_truck",
    toGraph: "world",
    toId: "world_firefighter",
    weight: 0.9,
    createdAt: NOW,
  },
  {
    id: asRelationshipId("rel_ft_learn"),
    type: "TEACHES",
    fromGraph: "learning",
    fromId: "learn_fire_truck",
    toGraph: "world",
    toId: "world_fire_truck",
    weight: 1,
    createdAt: NOW,
  },
  {
    id: asRelationshipId("rel_adv_requires_ft"),
    type: "REQUIRES",
    fromGraph: "adventure",
    fromId: "adventure_community_helpers",
    toGraph: "world",
    toId: "world_fire_truck",
    weight: 1,
    createdAt: NOW,
  },
  {
    id: asRelationshipId("rel_adv_unlocks"),
    type: "UNLOCKS",
    fromGraph: "world",
    fromId: "world_fire_truck",
    toGraph: "adventure",
    toId: "adventure_community_helpers",
    weight: 0.8,
    createdAt: NOW,
  },
];

const CHILD_KASE = asChildId("child_kase");

/**
 * Reference childhood timeline for Fire Truck — proves Living Discovery Card.
 * Ages 2 → 4 → 6 → 9 grow richer each revisit.
 */
export const SEED_MEMORY_NODES: MemoryNode[] = [
  {
    id: asMemoryNodeId("mem_ft_age2"),
    childId: CHILD_KASE,
    worldNodeId: asWorldNodeId("world_fire_truck"),
    timestamp: "2019-06-12T15:30:00.000Z",
    childAge: 2,
    adventureId: asAdventureNodeId("adventure_community_helpers"),
    photos: [
      {
        uri: "seed://photos/first_fire_truck.jpg",
        kind: "photo",
        capturedAt: "2019-06-12T15:30:00.000Z",
      },
    ],
    videos: [],
    voiceMemos: [
      {
        uri: "seed://voice/daddy_look.m4a",
        kind: "voice",
        capturedAt: "2019-06-12T15:31:00.000Z",
      },
    ],
    location: null,
    locationLabel: "Neighborhood street",
    weather: "sunny",
    peoplePresent: ["Dad"],
    emotion: "excited",
    notes: 'You called this a "red truck." Daddy look!',
    storyId: null,
    quizResults: [],
    activitiesCompleted: [],
    adventureProgress: {},
    favorite: true,
    tags: ["first"],
    linkedMemoryIds: [],
    discoveryLabel: "First Fire Truck",
    createdAt: "2019-06-12T15:30:00.000Z",
    updatedAt: "2019-06-12T15:30:00.000Z",
  },
  {
    id: asMemoryNodeId("mem_ft_age4"),
    childId: CHILD_KASE,
    worldNodeId: asWorldNodeId("world_fire_truck"),
    timestamp: "2021-09-18T14:00:00.000Z",
    childAge: 4,
    adventureId: asAdventureNodeId("adventure_community_helpers"),
    photos: [
      {
        uri: "seed://photos/fire_station.jpg",
        kind: "photo",
        capturedAt: "2021-09-18T14:00:00.000Z",
      },
    ],
    videos: [],
    voiceMemos: [],
    location: null,
    locationLabel: "City Fire Station",
    weather: null,
    peoplePresent: ["Mom", "Dad"],
    emotion: "curious",
    notes: "You learned firefighters use water.",
    storyId: null,
    quizResults: [],
    activitiesCompleted: ["Visited Fire Station"],
    adventureProgress: { adventure_community_helpers: 0.34 },
    favorite: false,
    tags: ["field_trip"],
    linkedMemoryIds: [],
    discoveryLabel: "Visited Fire Station",
    createdAt: "2021-09-18T14:00:00.000Z",
    updatedAt: "2021-09-18T14:00:00.000Z",
  },
  {
    id: asMemoryNodeId("mem_ft_age6"),
    childId: CHILD_KASE,
    worldNodeId: asWorldNodeId("world_fire_truck"),
    timestamp: "2023-03-04T16:20:00.000Z",
    childAge: 6,
    adventureId: asAdventureNodeId("adventure_community_helpers"),
    photos: [],
    videos: [],
    voiceMemos: [],
    location: null,
    locationLabel: "Home",
    weather: null,
    peoplePresent: ["Mom"],
    emotion: "proud",
    notes: "You knew what the ladder was for.",
    storyId: null,
    quizResults: [
      {
        questionId: "q_ft_6_team",
        correct: true,
        answeredAt: "2023-03-04T16:25:00.000Z",
      },
    ],
    activitiesCompleted: ["Fire Safety Lesson", "Completed Quiz"],
    adventureProgress: { adventure_community_helpers: 0.66 },
    favorite: false,
    tags: ["lesson"],
    linkedMemoryIds: [],
    discoveryLabel: "Fire Safety Lesson",
    createdAt: "2023-03-04T16:20:00.000Z",
    updatedAt: "2023-03-04T16:20:00.000Z",
  },
  {
    id: asMemoryNodeId("mem_ft_age9"),
    childId: CHILD_KASE,
    worldNodeId: asWorldNodeId("world_fire_truck"),
    timestamp: "2026-05-10T11:00:00.000Z",
    childAge: 9,
    adventureId: asAdventureNodeId("adventure_community_helpers"),
    photos: [],
    videos: [],
    voiceMemos: [],
    location: null,
    locationLabel: null,
    weather: null,
    peoplePresent: ["Grandpa"],
    emotion: "focused",
    notes: "You explained how emergency vehicles work. Grandpa taught you about the pump.",
    storyId: null,
    quizResults: [],
    activitiesCompleted: [
      "Learned How Fire Pumps Work",
      "Engineering Activity",
    ],
    adventureProgress: { adventure_community_helpers: 1 },
    favorite: true,
    tags: ["engineering"],
    linkedMemoryIds: [asMemoryNodeId("mem_ambulance_age8")],
    discoveryLabel: "Fire Pump Engineering",
    createdAt: "2026-05-10T11:00:00.000Z",
    updatedAt: "2026-05-10T11:00:00.000Z",
  },
  {
    id: asMemoryNodeId("mem_ambulance_age8"),
    childId: CHILD_KASE,
    worldNodeId: asWorldNodeId("world_ambulance"),
    timestamp: "2025-08-22T10:00:00.000Z",
    childAge: 8,
    adventureId: asAdventureNodeId("adventure_community_helpers"),
    photos: [
      {
        uri: "seed://photos/ambulance.jpg",
        kind: "photo",
        capturedAt: "2025-08-22T10:00:00.000Z",
      },
    ],
    videos: [],
    voiceMemos: [],
    location: null,
    locationLabel: "Hospital parking lot",
    weather: null,
    peoplePresent: ["Dad"],
    emotion: "calm",
    notes: "Dad took this picture of an ambulance.",
    storyId: null,
    quizResults: [],
    activitiesCompleted: [],
    adventureProgress: { adventure_community_helpers: 0.66 },
    favorite: false,
    tags: [],
    linkedMemoryIds: [asMemoryNodeId("mem_ft_age9")],
    discoveryLabel: "Ambulance",
    createdAt: "2025-08-22T10:00:00.000Z",
    updatedAt: "2025-08-22T10:00:00.000Z",
  },
  {
    id: asMemoryNodeId("mem_firefighter_age4"),
    childId: CHILD_KASE,
    worldNodeId: asWorldNodeId("world_firefighter"),
    timestamp: "2021-09-18T14:30:00.000Z",
    childAge: 4,
    adventureId: null,
    photos: [],
    videos: [],
    voiceMemos: [
      {
        uri: "seed://voice/hello_firefighter.m4a",
        kind: "voice",
        capturedAt: "2021-09-18T14:30:00.000Z",
      },
    ],
    location: null,
    locationLabel: "City Fire Station",
    weather: null,
    peoplePresent: ["Mom", "Firefighter Sam"],
    emotion: "shy",
    notes: "Mom recorded this voice memo saying hello to a firefighter.",
    storyId: null,
    quizResults: [],
    activitiesCompleted: [],
    adventureProgress: {},
    favorite: false,
    tags: [],
    linkedMemoryIds: [],
    discoveryLabel: "Firefighter",
    createdAt: "2021-09-18T14:30:00.000Z",
    updatedAt: "2021-09-18T14:30:00.000Z",
  },
];
